// Default
export const LOADING = "LOADING";
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";
export const CLEAN_UP = "CLEAN_UP";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_CLEAN_UP = "LOGIN_CLEAN_UP";

export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const LOGOUT_CLEAN_UP = "LOGOUT_CLEAN_UP";

export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const DASHBOARD_CLEAN_UP = "DASHBOARD_CLEAN_UP";

export const AGAMA_LOADING = "AGAMA_LOADING";
export const AGAMA_SUCCESS = "AGAMA_SUCCESS";
export const AGAMA_ERROR = "AGAMA_ERROR";
export const AGAMA_CLEAN_UP = "AGAMA_CLEAN_UP";

export const STATUS_PEGAWAI_LOADING = "STATUS_PEGAWAI_LOADING";
export const STATUS_PEGAWAI_SUCCESS = "STATUS_PEGAWAI_SUCCESS";
export const STATUS_PEGAWAI_ERROR = "STATUS_PEGAWAI_ERROR";
export const STATUS_PEGAWAI_CLEAN_UP = "STATUS_PEGAWAI_CLEAN_UP";

export const PENSIUN_LOADING = "PENSIUN_LOADING";
export const PENSIUN_SUCCESS = "PENSIUN_SUCCESS";
export const PENSIUN_ERROR = "PENSIUN_ERROR";
export const PENSIUN_CLEAN_UP = "PENSIUN_CLEAN_UP";

export const PENGHARGAAN_LOADING = "PENGHARGAAN_LOADING";
export const PENGHARGAAN_SUCCESS = "PENGHARGAAN_SUCCESS";
export const PENGHARGAAN_ERROR = "PENGHARGAAN_ERROR";
export const PENGHARGAAN_CLEAN_UP = "PENGHARGAAN_CLEAN_UP";
