export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_CLEAN_UP = "LOGIN_CLEAN_UP";

export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const LOGOUT_CLEAN_UP = "LOGOUT_CLEAN_UP";

export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const DASHBOARD_CLEAN_UP = "DASHBOARD_CLEAN_UP";

export const AGAMA_LOADING = "AGAMA_LOADING";
export const AGAMA_SUCCESS = "AGAMA_SUCCESS";
export const AGAMA_ERROR = "AGAMA_ERROR";
export const AGAMA_CLEAN_UP = "AGAMA_CLEAN_UP";
